name: .NET Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  patcher-tests:
    name: Run Liquip.Patcher.Tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: [ 8.0.x ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore Dependencies
        run: dotnet restore ./tests/Liquip.Patcher.Tests/Liquip.Patcher.Tests.csproj

      - name: Build Liquip.Patcher
        run: dotnet build ./src/Liquip.Patcher/Liquip.Patcher.csproj

      - name: Build Liquip.Patcher.Build
        run: dotnet build ./src/Liquip.Patcher.Build/Liquip.Patcher.Build.csproj
        
      - name: Build Liquip.Patcher.Tests
        run: dotnet build ./tests/Liquip.Patcher.Tests/Liquip.Patcher.Tests.csproj --configuration Debug --no-restore

      - name: Run Tests
        run: dotnet test ./tests/Liquip.Patcher.Tests/Liquip.Patcher.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Liquip.Patcher.Tests.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Liquip.Patcher.Tests-Results
          path: ./tests/Liquip.Patcher.Tests/TestResults/Liquip.Patcher.Tests.trx

  scanner-tests:
    name: Run Liquip.Scanner.Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: [ 8.0.x ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore Dependencies
        run: dotnet restore ./tests/Liquip.Scanner.Tests/Liquip.Scanner.Tests.csproj

      - name: Build Liquip.Patcher
        run: dotnet build ./src/Liquip.Patcher/Liquip.Patcher.csproj

      - name: Build Liquip.Patcher.Build
        run: dotnet build ./src/Liquip.Patcher.Build/Liquip.Patcher.Build.csproj
        
      - name: Build Liquip.Scanner.Tests
        run: dotnet build ./tests/Liquip.Scanner.Tests/Liquip.Scanner.Tests.csproj --configuration Debug --no-restore

      - name: Run Tests
        run: dotnet test ./tests/Liquip.Scanner.Tests/Liquip.Scanner.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Liquip.Scanner.Tests.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Liquip.Scanner.Tests-Results
          path: ./tests/Liquip.Scanner.Tests/TestResults/Liquip.Scanner.Tests.trx

  analyzer-tests:
    name: Run Liquip.Patcher.Analyzer.Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: [ 8.0.x ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore Dependencies
        run: dotnet restore ./tests/Liquip.Patcher.Analyzer.Tests/Liquip.Patcher.Analyzer.Tests.csproj

      - name: Build Liquip.Patcher.Analyzer.Tests
        run: dotnet build ./tests/Liquip.Patcher.Analyzer.Tests/Liquip.Patcher.Analyzer.Tests.csproj --configuration Debug --no-restore

      - name: Run Tests
        run: dotnet test ./tests/Liquip.Patcher.Analyzer.Tests/Liquip.Patcher.Analyzer.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Liquip.Patcher.Analyzer.Tests.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Liquip.Patcher.Analyzer.Tests-Results
          path: ./tests/Liquip.Patcher.Analyzer.Tests/TestResults/Liquip.Patcher.Analyzer.Tests.trx

  ilc-tests:
    name: Run Liquip.ilc.Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: [ 8.0.x ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++
 
      - name: Install Build Tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Restore Dependencies
        run: dotnet restore ./tests/Liquip.NativeWrapper/Liquip.NativeWrapper.csproj

      - name: Build Liquip.Patcher
        run: dotnet build ./src/Liquip.Patcher/Liquip.Patcher.csproj

      - name: Build Liquip.Patcher.Build
        run: dotnet build ./src/Liquip.Patcher.Build/Liquip.Patcher.Build.csproj

      - name: Build Liquip.NativeWrapper
        run: dotnet build ./tests/Liquip.NativeWrapper/Liquip.NativeWrapper.csproj --configuration Debug --no-restore


      - name: Build Liquip.ilc.Tests
        run: make -B -C ./tests/Liquip.ilc.Tests/

      - name: Run Tests
        working-directory: tests/Liquip.ilc.Tests/
        run: |
          ./output/main

